### ISSUE TITLE
addExtension should default to true or readme improvement 

### ISSUE THREAD

**Issue by AkselsLedins** [DataDog/serverless-plugin-datadog#144]
## Expected Behavior
- Custom metrics should be sent

## Actual Behavior
- Custom metrics are sent but not reported 

## Steps to Reproduce the Problem

  1. Use DD forwarder
  2. Send a custom metrics
  3. Look at the dashboard desperately not knowing why the custom metrics are not reported

## Specifications

  - Datadog Serverless Plugin version: latest
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Go
  
## Summary

Our use case: we were not using the datadog forwarder at first, then we started using it, using `flushMetricsToLogs` to `true` and precising the forwarder arn there: `forwarderArn`. While it improved the performance drastically, we lost **all** custom metrics. After a lot of back and forth with DD support, our team realized that the custom metrics using cloudwatch logs was deprecated. 

https://docs.datadoghq.com/serverless/custom_metrics/

Our changes required to retrieve the metrics:

```yml
# BEFORE

datadog:
    addLayers: true
    flushMetricsToLogs: true
    enableXrayTracing: true
    enableDDTracing: true
    enableTags: true
    forwarderArn: ${self:custom.DDForwarder}
    logLevel: "info"
    subscribeToApiGatewayLogs: false
    subscribeToHttpApiLogs: false
    subscribeToWebsocketLogs: false
    site: ${env:DATADOG_SITE}

# AFTER

datadog:
    addLayers: true
    flushMetricsToLogs: true
    enableXrayTracing: true
    enableDDTracing: true
    enableTags: true
    forwarderArn: ${self:custom.DDForwarder}
    logLevel: "info"
    subscribeToApiGatewayLogs: false
    subscribeToHttpApiLogs: false
    subscribeToWebsocketLogs: false
    site: ${env:DATADOG_SITE}
    addExtension: true
    apiKey: ${env:DATADOG_TOKEN}
```

<img width="560" alt="Screen Shot 2021-07-12 at 9 32 16 AM" src="https://user-images.githubusercontent.com/18367406/125249779-df878e80-e2f5-11eb-8783-883098a00793.png">

Then my question would, should we not enable `addExtension` to `true` or at least could we mention that in the README of this plugin (that with a forwarder and without the extension it doesn't work) ? 
We are not sure what is the extension doing so I'm not able to properly assess what should be the decision for the question above.

It took us close to a month to retrieve our metrics, we hope that our learnings and struggle would not be experienced by other teams.
