### ISSUE TITLE
Don't validate the forwarder ARN when using the sls package command 

### ISSUE THREAD

**Issue by dsmith-extron** [DataDog/serverless-plugin-datadog#150]
## Expected Behavior

I would like to call `sls package` to validate that that lambdas can be packaged and IaC generated without requiring credentials to an AWS account that will be used with `sls deploy`.

This is something that's useful if the build environment is separated from the deployment environment, and for almost all resources other than the `custom.datadog.forwarderArn` it works, and validation usually is at most on the form of an ARN. In this style, I would usually use a placeholder value like this one for the forwarder ARN: `arn:aws:lambda:us-east-1:012345678901:function:placeholder`.

Packages produced this way wouldn't deploy, but they would produce CloudFormation that passes for the `aws cloudformation validate-template` command.

## Actual Behavior

When I call `sls package`, if the `custom.datadog.forwarderArn` is not a real ARN accessible by the current environment, `DatadogForwarderNotFoundError` is thrown.

## Steps to Reproduce the Problem

  1. Specify a placeholder for the `custom.datadog.forwarderArn` value that's not a real lambda ARN
  2. Attempt to `sls package`

## Specifications

  - Serverless Framework version: "serverless": "2.30.3",
  - Datadog Serverless Plugin version: "serverless-plugin-datadog": "^2.29.0",
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 12
  
## Stacktrace
  
  The output is filtered through sls depending on the debug settings, but the throw originates here https://github.com/DataDog/serverless-plugin-datadog/blob/0175918822212696146694fa63cb6aa4ec24c233/src/forwarder.ts#L61

**Comment by dsmith-extron** [comment]
I see that there's a `custom.datadog.integrationTesting` property that can control this check, is there any way that it could be automatically supplied if the sls command is package instead of deploy?

**Comment by tianchu** [comment]
@dsmith-extron I don't think there is an existing way to automatically set `custom.datadog.integrationTesting` based on the sls command. However, you might be able to pass a custom argument to sls commands to control `custom.datadog.integrationTesting`?

TBH, I don't think the serverless plugin is designed to be used in a dev environment where you don't have a real Lambda function. Perhaps another workaround is to use a custom argument to enable/disable the plugin?

Regarding your original request, I'm not sure all the customers want that behavior, as I can imagine some customers might want to run `sls package` to preview if there is any issue with their serverless.yaml configurations and expect the plugin to report an error if accidentally have an incorrect forwarder arn.

**Comment by astuyve** [comment]
Instead perhaps would a conditional reference for the ARN work?
Many users might have multiple ARNs depending on the environment, so perhaps:
```
custom:
  forwarderArn:
    dev: <arn>
    prod: <arn>
    test: null
```

Then you could switch on the `stage` in the config:
```
custom:
  datadog:
    forwarderArn: ${self:custom.forwarderArn.${opt:stage, self:provider.stage}}
```

this would cause validation to skip: https://github.com/DataDog/serverless-plugin-datadog/blob/0175918822212696146694fa63cb6aa4ec24c233/src/forwarder.ts#L76

Please let me know if this solves the issue for you.

**Comment by dls314** [comment]
That would solve the issue.

I've used a different work around. I'm supplying the `integrationTesting` flag during CI.

```
custom:
  Configuration: ${{opt:Configuration, 'serverless.${{self:provider.stage}}.yml'}}
  DatadogIntegrationTesting: ${{file(${{self:custom.Configuration}}):DatadogIntegrationTesting, 'false'}}
  DatadogForwarderArn: ${{opt:DatadogForwarderArn, 'arn:aws:lambda:us-east-1:012345678901:function:placeholder'}}
  datadog:
    forwarderArn: ${{self:custom.DatadogForwarderArn}}
    integrationTesting: ${{self:custom.DatadogIntegrationTesting}}
```

**Comment by dsmith-extron** [comment]
That would solve the issue.

I've used a different work around. I'm supplying the integrationTesting flag during CI.

```
custom:
  Configuration: ${{opt:Configuration, 'serverless.${{self:provider.stage}}.yml'}}
  DatadogIntegrationTesting: ${{file(${{self:custom.Configuration}}):DatadogIntegrationTesting, 'false'}}
  DatadogForwarderArn: ${{opt:DatadogForwarderArn, 'arn:aws:lambda:us-east-1:012345678901:function:placeholder'}}
  datadog:
    forwarderArn: ${{self:custom.DatadogForwarderArn}}
    integrationTesting: ${{self:custom.DatadogIntegrationTesting}}
```
