### ISSUE TITLE
failed to send traces to Datadog Agent at http://localhost:8126

### ISSUE THREAD

**Issue by suwat-netprom** [DataDog/serverless-plugin-datadog#151]
## Expected Behavior
send log in aws cloudwatch to dataDog

provider: aws
runtime: python3.6
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-plugin-datadog
custom:
  datadog:
    addExtension: true
    apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
              

## Actual Behavior
failed to send traces to Datadog Agent at http://localhost:8126

## Steps to Reproduce the Problem

  1. sls deploy --stage dev --config config/serverless.dev.yml
  2. test endpoints apiGetway method get  exp. "url/getuser"
  3. goto aws cloudwatch view log

## Specifications

  - Serverless Framework version:  2
  - Datadog Serverless Plugin version:  "^2.29.0"
  - Lambda function runtime:  Python 3.6
  
## Stacktrace
  
  ```
  service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local
  - serverless-plugin-datadog

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  datadog:
    addExtension: true
    apiKey: xxxxxxxxxxxxxxxxxx
    addLayers: true
    logLevel: "info"
    enableDDTracing: true
    enableDDLogs: true
    enableTags: true
    injectLogContext: true
    site: "datadoghq.com"
  tableName: 'users-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: python3.6
  stage: dev
  profile: xxxxx
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "UsersDynamoDBTable", "Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}
    STATE_MANUAL: ${self:provider.stage}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getUser:
    handler: wsgi.handler
    events:
      - http: 'GET /users/{proxy+}'
  createUser:
    handler: wsgi.handler
    events:
      - http: 'POST /users'

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
  ```
