### ISSUE TITLE
Go support lambda extension

### ISSUE THREAD

**Issue by AkselsLedins** [DataDog/serverless-plugin-datadog#153]
Hello,

Per Datadog engineering team, the lambda extension is now supporting Go.
We used this plugin with Go successfully so far.

 **But**, using `addExtension` doesn't add a layer on a Go lambda function.
And, using the log forwarder works correctly but doesn't report the metrics correctly.

Any thoughts on this?

Thanks

**Comment by tianchu** [comment]
This plugin is designed to only support Python and Node.js for now (expanding to other runtimes in the future). You do have to add the extension layer on your own for Go Lambda functions.

https://docs.datadoghq.com/serverless/installation/go will be updated soon with instructions for using the Extension.

I can help post a sample application here later today.

**Comment by AkselsLedins** [comment]
Thank you very much @tianchu , I would be very keen to have an example of this plugin with Go and the `provided.al2` runtime

**Comment by tianchu** [comment]
Here is the preview version of the doc with updated instructions https://docs-staging.datadoghq.com/tian.chu/lambda-extension-for-go/serverless/installation/go

Sample application:

serverless.yaml
```yaml
service: test-go-extension

provider:
  name: aws
  region: ap-southeast-1

functions:
  test-go-extension:
    name: test-go-extension
    handler: handler
    runtime: provided.al2
    events:
      - http: GET hello
    environment:
      DD_API_KEY: <redacted>
      DD_ENV: dev
      DD_SERVICE: test-go-extension
      DD_VERSION: 0.0.1
      DD_SERVERLESS_LOGS_ENABLED: true
      DD_TRACE_ENABLED: true
```

app.go
```go
package main

import (
	"context"
	"time"

	"github.com/aws/aws-lambda-go/lambda"

	ddlambda "github.com/DataDog/datadog-lambda-go"
	"github.com/aws/aws-lambda-go/events"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

type testResponse struct {
	StatusCode int    `json:"statusCode"`
	Body       string `json:"body"`
}

func handleRequest(ctx context.Context, ev events.APIGatewayProxyRequest) (testResponse, error) {

	// submit a custom span
	s, _ := tracer.StartSpanFromContext(ctx, "test.span")
	time.Sleep(100 * time.Millisecond)
	s.Finish()

	ddlambda.Distribution("test.go.metric", 1)

	return testResponse{
		StatusCode: 200,
		Body:       "hello, world",
	}, nil
}

func main() {
	lambda.Start(ddlambda.WrapHandler(handleRequest, nil))
}
```

Build command

```bash
env GOOS=linux go build -ldflags="-s -w" -o handler app.go
```
