### ISSUE TITLE
[Feat] Ability to subscribe Kinesis data stream to send logs to Datadog

### ISSUE THREAD

**Issue by bryantbiggs** [DataDog/serverless-plugin-datadog#154]
## Expected Behavior
- Ability to specify Kinesis data stream to subscribe Serverless function CloudWatch logs and send to Datadog. Should be simple enough to just add an attribute for providing the Kinesis stream ARN (*I think) which the plugin will use to create the subscription

## Actual Behavior
- Not available today

https://www.datadoghq.com/blog/stream-logs-with-kinesis-firehose-and-datadog/

**Comment by tianchu** [comment]
@bryantbiggs you mind elaborating a bit more on your specific setup and use case?

**Comment by bryantbiggs** [comment]
definitely! 

we currently use the plugin across our environments (environment per AWS account) in conjunction with the lambda forwarder setup. our `serverless.yml` looks something like:
```yml
custom:
  datadog:
    apiKey: ${ssm:/aws/reference/secretsmanager/DatadogApiKey~true}
    ...
    forwarder: ${ssm:/datadog/log_forwarder_arn}
```

We create the log forwarders using Terraform and https://github.com/clowdhaus/terraform-aws-datadog-forwarders and the ARN of the forwarder is stored in an SSM param in each account (separate forwarder per environment/account/region)

however, in our production account we have peaks of very high activity which have led us to increase the reserved concurrency on the forwarder function to 800 and we still see some delay in processing under the peak load at that setting. this also steals from our total account concurrency for lambda invocations even though we have it set quite high (30k-50k). 

instead, what we would like to do for our production account is replace the lambda forwarder with a Kinesis stream that we can subscribe to the CloudWatch log groups and stream the logs to Datadog. this should remove the burden around the log forwarder in this environment and also reduce the amount of lag between logs being created and logs showing up in Datadog (please correct me if I am wrong). 

so maybe something like the following might work in our `serverless.yml`?

### nonprod
```yml
custom:
  datadog:
    apiKey: ${ssm:/aws/reference/secretsmanager/DatadogApiKey~true}
    ...
    forwarder_type: lambda
    forwarder: ${ssm:/datadog/log_forwarder_arn}
```

### prod
```yml
custom:
  datadog:
    apiKey: ${ssm:/aws/reference/secretsmanager/DatadogApiKey~true}
    ...
    forwarder_type: kinesis
    forwarder: ${ssm:/datadog/kinesis_stream_arn}
```
