### ISSUE TITLE
Adding subscriptions causing nested stack deploy failure.

### ISSUE THREAD

**Issue by thelpbogeyman** [DataDog/serverless-plugin-datadog#166]
## Expected Behavior
Deploy succeeds and all created log groups have a subscription filter to the Datadog lambda.
## Actual Behavior
Deploy fails with multiple errors creating subscription filters due to the log group not existing.
## Steps to Reproduce the Problem
  1. Deploy stack: `AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=$STAGE-profile sls package -s $STAGE`
## Specifications
  - Serverless Framework version: 1.44.1
  - Datadog Serverless Plugin version: 2.31.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): NodeJS 12.x 
## Stacktrace  
```
The specified log group does not exist. (Service: AWSLogs; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: b71275e5-babc-42af-bc72-ae74a7ceaef1; Proxy: null) 
```
## Details
Attempting to use the `serverless-plugin-datadog` to automatically create subscriptions to AWS log groups as my stack is deployed.
However, the deploy is failing, with multiple occurences of this error:
```
The specified log group does not exist. (Service: AWSLogs; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: b71275e5-babc-42af-bc72-ae74a7ceaef1; Proxy: null)
```
It doesn’t look like it is setting up the dependencies correctly, so I am getting all sorts of errors when CloudFormation attempts to create the subscription and the log group hasn’t been created.

There is one net-new function being added in this deploy and the `package.json` is using this:
```
"serverless-plugin-datadog": "^2.31.0"
```
Here’s my `serverless.yml` (custom section):
```yaml
  datadog:
    flushMetricsToLogs: true
    apiKey: ${self:custom.datadog-api-key}
    addLayers: true
    logLevel: ${self:custom.logLevel}
    enableXrayTracing: false  # Ultimately we want the dev teams to utilize XRay logging, but it's not in active use at this time.
    enableDDTracing: true
    enableDDLogs: true
    subscribeToApiGatewayLogs: true
    forwarderArn: ${self:custom.datadog-lambda-arn}
    enableTags: true
    injectLogContext: true
```
I am using nested stacks (`"serverless-plugin-split-stacks": "1.11.1"`), and all the correct pieces are defined, but from this example, although the logGroup is referenced, I am not sure that explicitly defines a dependency:
```json
    "myExampleLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/stackName-stageName-lambdaFunctionName"
      },
      "DependsOn": []
    },
    "myExampleLogGroupSubscription": {
      "Type": "AWS::Logs::SubscriptionFilter",
      "Properties": {
        "DestinationArn": "arn:aws:lambda:us-west-2:123456789012:function:datadog-ForwarderStack-Function-Arn",
        "FilterPattern": "",
        "LogGroupName": {
          "Ref": "myExampleLogGroup"
        }
      },
      "DependsOn": []
    }
```
In the “Properties” section above, it has a pointer to the lambda FUNCTION, but not the group, and although the log group Ref is there, the DependsOn is empty.
(account numbers changed, obviously)
**NOTE**: this is deploying to an existing stack (which I do not have the luxury of being able to delete & redeploy).
