### ISSUE TITLE
Layers defined at provider level are ignored

### ISSUE THREAD

**Issue by ojongerius** [DataDog/serverless-plugin-datadog#186]
## Expected Behavior

When configuring this plugin, in combination with `serverless-python-requirements` and layers configured the provider level, the layers at the provider layer the Datadog layers are added.

I've noticed the behaviour is correct when layers are added at the function level, as tested by the plugin in https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/layer.spec.ts#L130:

```js
  it("appends to the layer array if already present", () => {
    const handler = {
      handler: { runtime: "nodejs10.x", layers: ["node:1"] } as any,
      type: RuntimeType.NODE,
      runtime: "nodejs10.x",
    } as FunctionInfo;
    const layers: LayerJSON = {
      regions: { "us-east-1": { "nodejs10.x": "node:2" } },
    };
    applyLambdaLibraryLayers("us-east-1", [handler], layers);
    expect(handler.handler).toEqual({
      runtime: "nodejs10.x",
      layers: ["node:1", "node:2"],
    });
  });
```

However, at https://github.com/DataDog/serverless-plugin-datadog/blob/master/src/layer.ts#L63 you'll notice that layers are only retrieved from the FunctionInfo while they can *also* be configured at provider level:

```js
export function applyLambdaLibraryLayers(region: string, handlers: FunctionInfo[], layers: LayerJSON) {
  const regionRuntimes = layers.regions[region];
  if (regionRuntimes === undefined) {
    return;
  }

  for (const handler of handlers) {
    if (handler.type === RuntimeType.UNSUPPORTED) {
      continue;
    }

    const { runtime } = handler;
    const lambdaLayerARN = runtime !== undefined ? regionRuntimes[runtime] : undefined;
    let currentLayers = getLayers(handler);

    if (lambdaLayerARN) {
      currentLayers = pushLayerARN([lambdaLayerARN], currentLayers);
      setLayers(handler, currentLayers);
    }
  }
}
```

## Actual Behavior

The layers are provider level are "dropped", ie: DD layers are added, other layers no longer added to Lambda config

## Steps to Reproduce the Problem

Create sls project with following config:

```
service: toy-project

frameworkVersion: ">=1.2.0 <3.0.0"
variablesResolutionMode: 20210326

plugins:
  - serverless-plugin-datadog
  - serverless-python-requirements

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: python3.8
  region: ${opt:region, 'ap-southeast-2'}
  stage: ${opt:stage, 'dev'}
  layers:
    - Ref: PythonRequirementsLambdaLayer
functions:
  foo:
    handler: lambdas/foo.process
    description: Foo
    maximumEventAge: 1800
    maximumRetryAttempts: 0
custom:
  datadog:
    addLayers: true # default
  pythonRequirements:
    layer: true
```

Run `sls deploy --stage foo` and observe that only DD layers are added

## Specifications

  - Serverless Framework version: 2.61.0
  - Datadog Serverless Plugin version:  3.1.0
  - Lambda function runtime: Python 3.8

## Workaround

Provider extra layers used at function level
