### ISSUE TITLE
Tags not being automatically propagated to datadog logs

### ISSUE THREAD

**Issue by arielbachetti** [DataDog/serverless-plugin-datadog#187]
## Expected Behavior

All tags of the lambda function must be automatically inherited to the datadog logs. For example: if the lambda has the tag `asd: 'asdfg'` it should be in every log sent to datadog.

## Actual Behavior

When updated from plugin version `2.28.0` to `3.0.1`, lambdas without `name` property in serverless stopped to add their tags to datadog logs.

## Steps to Reproduce the Problem

1. Create a sls yml with the datadog plugin and tags.
2. Add one lambda without `name` (name will generate automatically) and one with `name`.
3. Deploy to AWS
4. Both lambdas will be correctly created in AWS with their tags.
5. Lambda with automatic `name` generation will ignore tags when logging to datadog.

Sls example:

```yml
service: ${self:custom.stackName}

plugins:
  - serverless-jetpack
  - '@rbilabs/serverless-jetpack'
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-plugin-tracing
  - serverless-plugin-datadog
  - serverless-plugin-tsoa
  - serverless-dynamodb-local
  - serverless-plugin-offline-dynamodb-stream
  - serverless-add-api-key
  - serverless-offline
  - serverless-offline-redis-server
  - serverless-offline-sns
  - serverless-domain-manager
  - serverless-plugin-ifelse

datadog:
  apiKey: ...
  addExtension: true

provider:
  tags:
    tag1: 'some-value-1'
    tag2: 'some-value-2'
    tag3: 'some-value-3'

functions:
  api:
    handler: api/index.handler
    provisionedConcurrency: ${self:custom.provisionedConcurrency}
    vpc:
      securityGroupIds: ...
      subnetIds: ...
    events:
      - http:
          path: /{any+}
          method: any
          private: true
    tags:
      'other-tag': 'other-tag-value-api'

  otherFunction:
    name: ${self:custom.stackName}-other-function
    handler: other-function/index.handler
    tags:
      'other-tag': 'other-tag-value-other-function'
    events: ...
```

## Specifications

  - Serverless Framework version: 2.61.0
  - Datadog Serverless Plugin version: 3.0.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14.17.3
