### ISSUE TITLE
SNS redrive queue receiving all messages

### ISSUE THREAD

**Issue by astuyve** [DataDog/serverless-plugin-datadog#228]
from @joaomirandasa

I find another issue too, when i user sns as event source for lambdas with redrive-policy associated, all events received in sns topic was redirected to deadLetterQueue. In my point of view sounds like datadog-plugin is changing something in `.yml` file witch causing anomalies in all functions

```
      - sns:
          arn: !Ref eventTopic
          topicName: eventTopic-${self:provider.stage}
          filterPolicy:
            event:
              - event:named
          redrivePolicy:
            deadLetterTargetRef: dispatchMTMessageQueue
```

_Originally posted by @joaomirandasa in https://github.com/DataDog/serverless-plugin-datadog/issues/226#issuecomment-1039124449_

**Comment by astuyve** [comment]
I'm attempting to replicate this now and will share my full `serverless.yml` and handler code.

**Comment by joaomirandasa** [comment]
I could not explain better but when version is downgrated everything get backs to normal, my opinion is an some rewrite of `serverless.yml` being executed by datadog extension

**Comment by astuyve** [comment]
Okay - thanks much @joaomirandasa!

For context, this plugin doesn't look for or modify SNS in any way (you can look for references here https://github.com/DataDog/serverless-plugin-datadog/search?q=sns&type=code), but to be sure I've attempted to replicate this (unsuccessfully) with the following setup and `serverless-plugin-datadog` v3.7.0:

`serverless.yml`
```yaml
service: aj-sns-redrive
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SQS:*
      Resource:
        - Fn::GetAtt: [demoDLQ, Arn]
    - Effect: Allow
      Action:
        - SNS:*
      Resource:
        - !Ref demoTopic
plugins:
  - serverless-plugin-datadog
custom:
  topicName: aj-sns-redrive-${opt:stage, "dev"}-topic
  dlqName: aj-sns-redrive-${opt:stage, "dev"}-dlq
  datadog:
    apiKey: 1234
    addExtension: true
    addLayers: true
    captureLambdaPayload: true
    logLevel: debug
functions:
  snsPublisher:
    handler: handler.snsPublisher
    environment:
      DEMO_TOPIC_ARN: !Ref demoTopic
    events:
      - httpApi:
          path: /publishTopic
          method: post
  snsWorker:
    handler: handler.snsWorker
    events:
      - sns:
          arn: !Ref demoTopic
          topicName: ${self:custom.topicName}
          redrivePolicy:
            deadLetterTargetRef: demoDLQ
resources:
  Resources:
    demoTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.topicName}
    demoDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.dlqName}

```
Function code
`handler.js`
```javascript
'use strict';
const AWS = require('aws-sdk')
AWS.config.update({region: 'sa-east-1'});

// Create an sns service object
const sns = new AWS.SNS({apiVersion: '2012-11-05'});

module.exports.snsPublisher = async (event) => {
  const body = JSON.parse(event.body)

  await sns.publish({
    Message: JSON.stringify(body),
    TopicArn: process.env.DEMO_TOPIC_ARN
  }).promise()
  return {
    statusCode: 200,
    headers:
    {
      "content-type": "application/json"
    },
    body: JSON.stringify({status: 'pushed', body})
  }
}

module.exports.snsWorker = async (event) => {
  console.log(`sns worker received event: `, event.Records)
  const record = JSON.parse(event.Records[0].Sns.Message)
  console.log(`RECORD: ${record}`)
  if (record && record.throw) {
    throw new Error('ahhh')
  }
  return
}
```
Here are the results.
As you can see, a regular payload is sent fine:
![image](https://user-images.githubusercontent.com/1598537/153923822-112e81f1-98d1-45b6-b4ac-d7ff94db33b1.png)

And fully traced in Datadog, including the message being received, and you can verify that with the payload I've displayed:
![image](https://user-images.githubusercontent.com/1598537/153924080-83670e43-c5d0-4509-aedb-bdfeadf97bc3.png)

And when I instruct the function to throw (to trigger redrive), you can see the error from the function (so it is being invoked), and you can see the attempt to retry (longer span underneath the first yellow span):
![image](https://user-images.githubusercontent.com/1598537/153924397-438937e8-04c7-437c-8d80-c1efc617bcf7.png)

I've confirmed this using Cloudwatch logs as well, here is the payload being logged as well as the error I'm throwing intentionally when the `throw` attribute of the payload is set:
![image](https://user-images.githubusercontent.com/1598537/153925271-6fc73c57-b493-407b-99ef-16b4e7b603f9.png)
So far the redrive seems normal, but after 23 days it will go to the DLQ as per the [docs](https://docs.aws.amazon.com/sns/latest/dg/sns-message-delivery-retries.html)


To confirm, please recreate a nodejs project with my configuration and verify my findings. If you make changes, please add them in a comment here.

Thanks again!
