### ISSUE TITLE
Unable to use datadog-lambda-js with webpack

### ISSUE THREAD

**Issue by raghav-fabric** [DataDog/serverless-plugin-datadog#270]
## Overview
We're trying to use serverless-plugin-datadog on our service and our primary objective is to send custom metrics to datadog. We're using webpack to build our service to push it to lambdas. Before I explain further, we did find webpack had some issues with datadog-lambda-js, but we have included what ever has been mentioned [here](https://docs.datadoghq.com/serverless/guide/serverless_tracing_and_webpack/), on datadog's website for Node JS and webpacks.

## Errors
When we exclude datadog-lambda-js and perform the build with serverless deployment, the function with datadog-lambda-js library being used, throws us an error as : **Error: Cannot find module 'datadog-lambda-js**. However, when we run the same code on local, we include datadog-lambda-js on our dev dependencies, and everything works as expected. It's just the lambda that throws errors. 

## Additional details

1. We have imported serverless-plugin-datadog on our code.
2. Once deployed to lambdas, we do see the datadog lambda layers.
3. If we use these layers on a manually created lambda, and use datadog-lambda-js, everything works as expected.

## Our code and process

**Serverless file: **
```
plugins:
  - serverless-plugin-warmup
  - serverless-plugin-datadog
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  - serverless-step-functions
  - serverless-plugin-resource-tagging
  - serverless-dynamo-stream-plugin

custom:
  datadog:
    addExtension: true
    addLayers: true
    apiKey: <my-dd-key>
    flushMetricsToLogs: false
    enabled: true
    injectLogContext: true
    logLevel: debug
    enableDDTracing: false
  webpack:
    webpackConfig: /webpack.config.js
    includeModules:
      forceExclude: 
        - datadog-lambda-js
        - dd-trace
    packagerOptions: 
      scripts:
        - rm -rf node_modules/datadog-lambda-js node_modules/dd-trace
    packager: npm
```

**Webpack file (excludes value)**: `externals: [nodeExternals(), "dd-trace", "datadog-lambda-js"],`

**Datadog file**
```
const { datadog, sendDistributionMetric, sendDistributionMetricWithDate } = require('datadog-lambda-js');

exports.hello = async function hello(event, context) {
    console.log("Running metrics")
    sendDistributionMetricWithDate(
      "<my-metric-name>",       // Metric name
      1,                                         // Metric value
      new Date(Date.now()),                            
      "tag1:val1",
      "tag2:val2",  // Associated tags
      
    );
    console.log("Closing metrics")
    return {
      statusCode: 200,
      body: "hello, dog!",
    };
  }
```

## Specifications

  - Serverless Framework version:  2.62.0
  - Datadog Serverless Plugin version: "serverless-plugin-datadog": "^5.1.1",
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14.x

## References:

1. [Sending Custom metrics with serverless to datadog](https://docs.datadoghq.com/serverless/installation/nodejs/?tab=serverlessframework)
2. [StackOverflow Question](https://stackoverflow.com/questions/72392329/getting-error-error-cannot-find-module-datadog-lambda-js?noredirect=1#comment127887214_72392329)

Please let me know If I'm missing something here, but we've been trying from sometime now and still facing the same issues where datadog-lambda-js is not being recognised on our function even when we have the lambda layers.

**Comment by raghav-fabric** [comment]
> Hi @raghav-fabric - thanks for reaching out. I'll reproduce with your example and try to be of assistance.

Thanks @astuyve Let me know if you want me to share any additional code from my end. 
Really appreciate your help on this. 👍

**Comment by DarcyRaynerDD** [comment]
Generally, if you are using the serverless-webpack plugin, we should be force excluding dd-lambda-js from your dependencies when you [bundle and deploy:](https://github.com/DataDog/serverless-plugin-datadog/blob/11fb44e7c5b4e06daada966c5a7b469fc4f8b8bd/src/env.ts#L262). So it might potentially be a bug or edge case

**Comment by DarcyRaynerDD** [comment]
Is dd-lambda-js/dd-trace-js installed locally in your package.json while developing?

**Comment by raghav-fabric** [comment]
@DarcyRaynerDD  Thanks for checking on this.
but datadog-lambda-js and dd-trace-js both are not included in my package.json. 
They're removed while deploying. 
I've also removed them using webpack scripts (as mentioned here : https://docs.datadoghq.com/serverless/guide/serverless_tracing_and_webpack/)

**Comment by astuyve** [comment]
Hi @raghav-fabric - one thing to check is placing `serverless-plugin-datadog` at the end of the list of your plugins, this will run our plugin last, ensuring webpack has finished before the datadog handler redirection is applied.

Given that change, I can't reproduce your issue with the following minimal example:
`src/handler.js`
```javascript
const { datadog, sendDistributionMetric, sendDistributionMetricWithDate } = require('datadog-lambda-js');

exports.hello = async function hello(event, context) {
    console.log("Running metrics")
    sendDistributionMetricWithDate(
      "<my-metric-name>",       // Metric name
      1,                                         // Metric value
      new Date(Date.now()),
      "tag1:val1",
      "tag2:val2",  // Associated tags

    );
    console.log("Closing metrics")
    return {
      statusCode: 200,
      body: "hello, dog!",
    };
  }
```

`webpack.config.js`
```javascript
var nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: './src/handler.js',
  // use webpack-node-externals to exclude all node dependencies.
  // You can manually set the externals too.
  // output: {
  //   path: __dirname + '/src',
  //   filename: '[name].js'
  // },
  externals: [nodeExternals(), "dd-trace", "datadog-lambda-js"],
};
```
`serverless.yml`
```yaml
service: js-webpack
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-webpack
  - serverless-plugin-datadog

custom:
  datadog:
    addExtension: true
    addLayers: true
    apiKey: <my API Key>
    logLevel: debug
  webpack:
    webpackConfig: /webpack.config.js
    includeModules:
      forceExclude:
        - datadog-lambda-js
        - dd-trace
    packagerOptions:
      scripts:
        - rm -rf node_modules/datadog-lambda-js node_modules/dd-trace
    packager: npm

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
```

This results in a 200ok response, metrics being delivered, traces collected, and things generally working:
![image](https://user-images.githubusercontent.com/1598537/171505216-614c59b8-ee1c-4030-9d66-230dcf78accb.png)

If the datadog node layer is present, I'm unclear how the require would fail in this case.
