### ISSUE TITLE
Is there any config mapping to config `ExcludeAtMatch` in this plugin?

### ISSUE THREAD

**Issue by skyforeverRivian** [DataDog/serverless-plugin-datadog#278]
**Is there any config mapping to config `ExcludeAtMatch` in this plugin?**

There is config in dd config
https://github.com/DataDog/datadog-serverless-functions/blob/a14e7e6b28597a917bed332afe292c5bf9719d2d/aws/logs_monitoring/template.yaml#L135

is there any possible passing matcher from this plugin?

**Comment by astuyve** [comment]
Hi, this should work out of the box. You can add a `datadog.yaml` configuration file into your project with this configuration, and the Datadog Extension will pick it up and apply it.

The `datadog.yaml` file should be in the same directory of your `serverless.yml` file.

**Comment by skyforeverRivian** [comment]
@astuyve thank you for replying; in `serverless.yml` file, there are something like 
```
custom:
  datadog:
    apiKeySecretArn: "{Datadog_API_Key_Secret_ARN}"
    enableXrayTracing: false
    enableDDTracing: true
    enableDDLogs: true
    subscribeToAccessLogs: true
    forwarderArn: arn:aws:lambda:us-east-1:000000000000:function:datadog-forwarder
    exclude:
      - dd-excluded-function
 ```

should I re-do this similar thing in `datadog.yaml`?
