### ISSUE TITLE
MalformedHandlerName on single function deployment

### ISSUE THREAD

**Issue by rizowski** [DataDog/serverless-plugin-datadog#285]
## Expected Behavior
Function to execute without errors. We just upgraded to node 16 which made the dd plugin v4.1.1 to stop working. So I tried upgrading to v5 so we can start using it again and pushed it out to a single function. But I started getting the error below. I'm a bit timid to push out all of our functions when this is happening.

Function executes fine without the datadog layers.

## Actual Behavior
Throws an exception around a malformed handler name

## Steps to Reproduce the Problem

  1. serverless deploy --stage [whatever] -f functionName

## Specifications
  - Serverless Framework version: `3.19.0`
  - Datadog Serverless Plugin version: `latest (5.3.0)`
  - Lambda function runtime (Python 3.7, Node 10, etc.): `node16`
  - architecture: `x86_64`

Function Naming: 
- `generateUserPermissions`

Plugins being used:
  - serverless-webpack

Datadog config:
```
  datadog:
    enabled: ${strToBool(${env:DATA_DOG_PLUGIN_ENABLED, false})}
    apiKey: ${env:DATA_DOG_API_KEY}
    addExtension: true
    logLevel: "error"
```

  
## Stacktrace
  
  ```
 {
    "errorType": "Runtime.MalformedHandlerName",
    "errorMessage": "Bad handler",
    "stack": [
        "Runtime.MalformedHandlerName: Bad handler",
        "    at MalformedHandlerName.ExtendedError [as constructor] (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:113:28)",
        "    at new MalformedHandlerName (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:139:42)",
        "    at _splitHandlerString (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:93:15)",
        "    at /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:334:33",
        "    at step (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:43:23)",
        "    at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:24:53)",
        "    at /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:18:71",
        "    at new Promise (<anonymous>)",
        "    at __awaiter (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:14:12)",
        "    at load (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:327:12)"
    ]
}
  ```

**Comment by astuyve** [comment]
Hi @rizowski - thanks for reaching out. Could you add a couple details so we can help debug this?
1. The `serverless.yml` config for your function (omitting anything sensitive)
2. The `DD_HANDLER` environment variable as seen in the AWS console for your function

Thanks!

**Comment by rizowski** [comment]
@astuyve 
Looks like `DD_HANDLER ` isn't set

Is there anything else you might want to look at?
```
generateUserPermissions:
  handler: functions/streams/permissions/index.run
  environment:
    // inherited from global
    DD_API_KEY: ${env:DATA_DOG_API_KEY}
    DD_ENV: ${self:provider.stage}
    DD_SERVICE: ${self:service}
  events:
    - stream:
        type: dynamodb
        batchSize: 5
        maximumRetryAttempts: 0
        enabled: true
        arn: streamARN
    - stream:
        type: dynamodb
        batchSize: 5
        maximumRetryAttempts: 0
        enabled: true
        arn: streamARN
```
