### ISSUE TITLE
datadog.yml and ExcludeAtMatch

### ISSUE THREAD

**Issue by michaelwclark** [DataDog/serverless-plugin-datadog#295]
## Expected Behavior
when datadog.yml is present in the root the exclude/include log filtering should be utilized.

## Actual Behavior
no filtering.

It's possible I'm doing this wrong, but I've tried about 30 variations and can't get the start/end filtering to work at all which is greatly inflating my log injestion needs.

```yaml
Description: Pushes logs, metrics and traces from AWS to Datadog.
Parameters:
  ExcludeAtMatch: '"(START|END) RequestId:\s'
```

also 

```yaml
Description: Pushes logs, metrics and traces from AWS to Datadog.
Parameters:
  ExcludeAtMatch: '(START|END) RequestId:'
```

I have a lerna monorepo in which i keep lambda services in nested directories under `/services` folder. Ex `/services/lambdaA/lambdaA.js`

I have placed the datadog.yml both at the root of my project `/` as well as in each of the folders that contain my serverless.yml for the lambdas ex: `/services/lambdaA/datadog.yml`

No change in the logs coming in.

relevent serverless.yml custom section:
```yaml
  datadog:
    addLayers: true
    env: ${sls:stage}
    service: my-service-name
    version: 1.0.0
    site: datadoghq.com
    captureLambdaPayload: true
 ```

## Steps to Reproduce the Problem

  1. add datadog.yml to project root
  1. deploy
  1. view logs, still have start/end entries.

## Specifications

  - Serverless Framework version: Framework Core: 3.21.0 (local) 3.17.0 (global) Plugin: 6.2.2 SDK: 4.3.2
  - Datadog Serverless Plugin version:   "^5.5.0"
  - Lambda function runtime (Python 3.7, Node 10, etc.):  runtime: nodejs14.x
