### ISSUE TITLE
Disable Trace Logging

### ISSUE THREAD

**Issue by samchungy** [DataDog/serverless-plugin-datadog#298]
Hey guys I was hoping you could help me disable these logs

<img width="465" alt="image" src="https://user-images.githubusercontent.com/18017094/189005709-fe661e24-08cf-4cd0-b869-31a91d1a987f.png">

We currently have this config setup. How do I prevent these from appearing in our logs? I assume these are from dd-trace?

```
  datadog:
    apiKeySecretArn: ${self:custom.env.values.datadogApiKeyArn}
    enableDDLogs: false
    exclude:
      - WorkerPreHook
    version: ${env:BUILDKITE_BUILD_NUMBER}
```
