### ISSUE TITLE
service & env are ignored in "monitors" configuration

### ISSUE THREAD

**Issue by LironEr** [DataDog/serverless-plugin-datadog#302]
## Expected Behavior
New monitor should use the service name & env configured in `custom.datadog`

## Actual Behavior
Monitor ignores the custom names and uses the serverless service name and current stage.

## Steps to Reproduce the Problem

  1. Add service or env configurations to `custom.datadog`
```
datadog:
  apiKey: "aaaa"
  appKey: "aaaa"
  service: "my-service"
  version: "1.0.0"
  monitors:
    - high_error_rate:
        tags: ["team:some-team"]
```

  2. deploy

After deploy I saw that the monitor service name is the serverless service name instead of the one configured in `custom.datadog.service`

## Specifications

  - Serverless Framework version: 3.18.2
  - Datadog Serverless Plugin version: 5.8.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): python 3.9
