### ISSUE TITLE
Using apiKeySecretArn logs an error during deployment

### ISSUE THREAD

**Issue by cjaube** [DataDog/serverless-plugin-datadog#305]
## Expected Behavior
It should use the apiKeySecretArn and not log an error.

## Actual Behavior
It logs an error: `Skipping installing GitHub integration because Datadog credentials were not found. Please set either DATADOG_API_KEY in your environment, or set the apiKey parameter in Serverless.`

## Steps to Reproduce the Problem

  1. Create a secret and paste datadog API key in (raw key, not json).
  2. Copy the ARN
  3. Add to serverless config:
```
custom:
  ...  
  datadog:
    site: 'datadoghq.com'
    apiKeySecretArn: 'arn:aws:secretsmanager:us-east-1:************:secret:test-pip-datadogSecret-******'
```
  5. Assume a cross-account deployment role with full permissions and deploy
  7. You get an error saying that you didn't set the apiKey. The error suggests that it ignored the fact that the apiKeySecretArn is set.

## Specifications

  - Serverless Framework version: 3.23.0
  - Datadog Serverless Plugin version: 5.9.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14
