### ISSUE TITLE
Serverless Common Resource Tags and DataDog Dashboards

### ISSUE THREAD

**Issue by StanBorbatTR** [DataDog/serverless-plugin-datadog#307]
Our organization requires a large set of AWS resource tags to be applied to every resource. We usually delcare them inside the
`provider.stackTags` attribute. However with this approach, Serverless doesn't allow us to append or override tags on indivudual
resources. This makes it very difficult for us to monitor applications managed with the Serverless Framework. Please follow along with the example below:

- All AWS resources are tagged with the following set of tags, set on `provider.stackTags`
    - application: [my-shiny-app]
    - service: [my-shiny-app]
    - env: [dev|qa|prod]
    - version: [v1.1.1]
    - ...many others
- All AWS resources are deployed with an `${env}-${application}-` prefix to avoid collisions between environments
- A DataDog dashboard for this application is templated by the `${env}` tag

I can now add a graph to the dashboard that will scope to all queues, but I can't add one that will scope to a single queue.
The only tag that varies between the resourced deployed by the application is the resource name. For example the `queuename`
tag. However this tag is always prefixed with the `${env}-${application}-`, and the DataDog doesn't seem to allow using the
templated variables for the tag names.

Ideally, I would like Serverless or the DataDog plugin to give us an ability to vary the `service` tag between the resources
deployed by the application. This way I can scope down the graphed metrics by the templated `$env` tag, and static
`application:my-shiny-app` `service:my-shiny-app-ingest-queue`.

Is this a feature that can somehow be addressed using the DataDog Serverless plugin or any other way?

**Comment by StanBorbatTR** [comment]
After trying another approach, I realized that this is actually possible using the combination os `provider.stackTags` and the tags property on the CloudFormation resources. The property seems to override the tag defined in `provider.stackTags`:

```
provider:
  stackTags:
    application: ${self:custom.application}
    service: ${self:custom.application}
    env: ${self:custom.envName}
    version: ${self:custom.buildVersion}

resources:
  Resources:
    ExampleQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.envName}-${self:custom.application}-example.fifo
        FifoQueue: true
        VisibilityTimeout: 30
        MessageRetentionPeriod: 1209600
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - EntitlementsQueueDLQ
            - Arn
          maxReceiveCount: ${self:custom.config.maxRetries}
        Tags:
          - Key: service
            Value: sqs-${self:custom.application}-example
```
