### ISSUE TITLE
Instances of duplicated logs and metrics

### ISSUE THREAD

**Issue by sambegin** [DataDog/serverless-plugin-datadog#329]
## Expected Behavior
Never have duplicated logs and metrics in Datadog

## Actual Behavior
We see duplicated logs and metrics sent (or consumed) by Datadog with the exact same code and build.
- The `dd.trace_id` is exactly the same between logs
- The `lambda.request_id` is exactly the same between logs
- **The id property is different** and is the only property that is
- The timestamps are to the hundredth of a millisecond the same
- We know that the code logic did not run twice as we've double-checked all of our results
- The metrics number we've sent has been duplicated (that's how we discovered the issue since we do some balance calculations based on them). 

Please have a look at what we see in Datadog. Each duplicated instances of timestamp have in fact run only once: 
<img width="395" alt="Screenshot 2022-12-22 at 10 09 11 AM" src="https://user-images.githubusercontent.com/6645382/209165863-b26f9065-85f0-4d85-940c-fe0f937b2dd0.png">

## Steps to Reproduce the Problem

  1. Super hard to reproduce. We have a scheduled task that runs every day at the same hour. Sometime we see our metrics going off and that's when we know we have the issue.
```
  scheduledInvoiceTask:
    tags:
      speed: normal
    handler: src/handlers/scheduledInvoiceTask.scheduledInvoiceTask
    events:
      - schedule:
          enabled: ${self:custom.cronEnabled.${opt:stage}}
          rate: cron(11 13 * * ? *)
```

We're essentially looking for advice and are open to trying some recommended stuff to pinpoint the issue.

## Specifications

  - Serverless Framework version: 3.24.1
  - Datadog Serverless Plugin version: 5.10.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 16
  
Thank you!
