### ISSUE TITLE
Using default monitor's - the variables in template are not replaced by values

### ISSUE THREAD

**Issue by cforce** [DataDog/serverless-plugin-datadog#345]
Using below default monitors
```
  monitors:
    - timeout:
    - out_of_memory:
    - high_iterator_age:
    - high_cold_start_rate:
    - high_throttles:
    - increased_cost:
```
the "{{functionname.name}} in {{region.name}} for {{aws_account.name}}" is no replaced with values,
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/393286/215539735-163c9e8c-d55d-4087-8485-358c99ce273d.png">

I have no idea why and how this  {{XXX}}  masking (shall) work ad this kind of variable masking is completey unknown to the serverlessframework isn' it?  I know something like ${YYY:XXX} where YYY cpuld be env, param,self, opt ... according to  https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-serverless-core-variables. Buts still also unlcear where this vars shall be set. I didn't find any hints here or on  https://docs.datadoghq.com/serverless/libraries_integrations/plugin/#to-create-a-recommended-monitor-with-the-default-values
