### ISSUE TITLE
DD_SERVICE is overwritten with the application name

### ISSUE THREAD

**Issue by yyamanoi1222** [DataDog/serverless-plugin-datadog#445]
## Expected Behavior
if a value is set, DD_SERVICE is not overwritten.

## Actual Behavior
DD_SERVICE is overwritten with the application name.

## Steps to Reproduce the Problem

  1. serverless.yml

```yml
service: serverless-dd
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DD_SERVICE: 'test-app'
functions:
  hello:
    handler: handler.hello

```

  2. Run sls deploy
  3. Expected value of DD_SERVICE is "test-app" but, actually "serverlerss-dd"
## Specifications

  - Serverless Framework version: 3.36.0
  - Datadog Serverless Plugin version:  5.52.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs18.x
  
## Stacktrace
  
  ```
  Paste here
  ```
