### ISSUE TITLE
Logs are not excluded with `datadog.yaml`

### ISSUE THREAD

**Issue by kvin5529** [DataDog/serverless-plugin-datadog#473]
## Expected Behavior

DD Logs needs to be excluded based on the pattern given in `datadog.yaml`

```
  datadog:
    addExtension: true
    injectLogContext: true
    flushMetricsToLogs: true
    enableTags: true
    logLevel: info
    apiKey: ${file(./serverless.env.yml):${opt:stage}.DATADOG_API_KEY}
```

```
plugins:
  - serverless-plugin-datadog
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-aws-alerts
```

`datadog.yaml` - This file is added in root directory

```
logs_config:
  processing_rules:
    - type: exclude_at_match
      name: exclude_start_and_end_logs
      pattern: (START|END) RequestId
```

## Actual Behavior

Still `START RequestId` and `End RequestId` are still visible

After running `sls deploy --verbose -s dev`, what I can see as the artifacts are as follows.
```
.
├── compiled-cloudformation-template.json
├── serverless-state.json
└── <application>.zip
    ├── node_modules
    └── src
```

But I have included `datadog.yaml` at the root directory where I have `serverless.yml`

## Specifications

  - Serverless Framework version: 3 (^3.38.0)
  - Datadog Serverless Plugin version: ^5.25.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node.js 20.x

**Comment by kvin5529** [comment]
I found the issue. Here I've missed to include `datadog.yaml` file when packaging with `serverless deploy`

So I updated the `serverless.yaml` as follows with an inclusion to preserve `datadog.yaml`.

```
package:
  exclude:
    - '**/*.ts'
    - 'test/**'
    - '*'
  include:
    - 'datadog.yaml'
```
