### ISSUE TITLE
Plugin configuration with only log forwarding (via forwarder) and monitors should not require wrapper

### ISSUE THREAD

**Issue by max-lobur** [DataDog/serverless-plugin-datadog#480]
## Expected Behavior
Extensions/Layers/Library should not be not required when using plugin only to link log forwarder and setup monitors.

## Actual Behavior
Lambda error:
```
/opt/datadog_wrapper: does not exist
```

## Steps to Reproduce the Problem
```
  datadog:
    enabled: true
    site: us5.datadoghq.com
    apiKey: <>
    appKey: <>
    enableDDLogs: false
    enableXrayTracing: false
    enableDDTracing: false
    enableASM: false
    enableProfiling: false
    enableSourceCodeIntegration: false
    enableColdStartTracing: false
    uploadGitMetadata: false
    addLayers: false
    addExtension: false
    encodeAuthorizerContext: false
    decodeAuthorizerContext: false
    subscribeToAccessLogs: true
    subscribeToExecutionLogs: true
    forwarderArn: <arn>
    failOnError: true
    logLevel: DEBUG
    service: api
    env: dev
    monitors:
      - high_error_rate: {}
      - timeout: {}
      - high_throttles: {}
```

```
sls deploy
```

## Specifications

  - Serverless Framework version: 
Framework Core: 3.38.0 (local) 3.38.0 (global)
Plugin: 7.2.0
SDK: 4.5.1
  - Datadog Serverless Plugin version: 5.60.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): python3.10
  
## Stacktrace
  
  ```
/opt/datadog_wrapper: does not exist
  ```
