### ISSUE TITLE
Loglevel set to error not working

### ISSUE THREAD

**Issue by earlybirdeng** [DataDog/serverless-plugin-datadog#541]
## Expected Behavior
When i set the logLevel to error in the plugin it should only emit error logs to data dog

## Actual Behavior
All my INFO logs are being sent to datadog.

## Steps to Reproduce the Problem
```
custom:
  staged: ${self:custom.stageVars.${self:provider.stage}}
  stageVars:
    dev:
      dd_enabled: false
    prod:
      dd_enabled: true
  datadog:
    enabled: ${self:custom.staged.dd_enabled, true}
    apiKey: ${self:custom.datadog_api_key.key}
    site: us5.datadoghq.com
    logLevel: error
    enableXrayTracing: false
    enableDDTracing: false
    enableDDLogs: true
    subscribeToAccessLogs: true
    exclude:
      - dd-excluded-function
```

I even tried manually setting the env var
```
  environment:
    DATADOG_API_KEY: ${self:custom.datadog_api_key.key}
    DD_LOGS_INJECTION: true
    DD_LOG_LEVEL: error
```

## Specifications

  - Serverless Framework version:  4.4.5
  - Datadog Serverless Plugin version: ^5.71.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): node 18
  
## Stacktrace
  
  ```
  Paste here
  ```
