### ISSUE TITLE
Add a configuration for DD_SERVERLESS_FLUSH_STRATEGY

### ISSUE THREAD

**Issue by 0angelic0** [DataDog/serverless-plugin-datadog#563]
## Expected Behavior

The serverless-plugin-datadog should provide a configuration option to set the DD_SERVERLESS_FLUSH_STRATEGY environment variable, which controls how the Datadog tracer flushes data from Lambda functions. This would allow users to customize the flush behavior based on their needs.

## Actual Behavior

The plugin currently does not expose any configuration option to set the DD_SERVERLESS_FLUSH_STRATEGY environment variable, limiting users' ability to control how traces are flushed to Datadog.

## Steps to Reproduce the Problem

1.Install serverless-plugin-datadog v5.75.0
2.Configure the plugin in serverless.yml
3.Review available configuration options in the documentation
4.Note that there is no option to configure DD_SERVERLESS_FLUSH_STRATEGY

## Impact

Without the ability to configure the flush strategy:
- Users cannot optimize trace delivery based on their specific use cases
- No control over when traces are sent to Datadog
- Default behavior may not be optimal for all scenario

## Specifications

  - Serverless Framework version: Any
  - Datadog Serverless Plugin version: v5.75.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): All supported runtime
  
## Stacktrace
  
N/A

## Related Documentations

[Datadog Lambda Extension Documentation on Flush Strategies](https://docs.datadoghq.com/serverless/libraries_integrations/extension/#overhead)
[Current Plugin Configuration Options](https://github.com/DataDog/serverless-plugin-datadog?tab=readme-ov-file#configuration-parameters)

## Proposed Solution

Add a new configuration option in the plugin that allows setting the DD_SERVERLESS_FLUSH_STRATEGY environment variable, similar to other environment variable configurations already supported by the plugin.

**Comment by purple4reina** [comment]
Hi @0angelic0, thanks so much for the detailed issue. I very much agree that users of this plugin need the ability to set `DD_SERVERLESS_FLUSH_STRATEGY` on their lambda functions. You've described one solution, which is to add a new configuration option.

Even without a configuration option, you can still set `DD_SERVERLESS_FLUSH_STRATEGY` on your lambda functions by including it directly as an environment variable. Here is how you would do it

```yaml
service: custom-flushing-service

provider:
  name: aws
  runtime: python3.9
  environment:
    DD_SERVERLESS_FLUSH_STRATEGY: 'periodically,60000'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  myFunction:
    handler: handler.handler
```

Notice that I've added the `DD_SERVERLESS_FLUSH_STRATEGY` under an `environment` heading. This environment heading can also be set on a per function level, as

```yaml
functions:
  myFunction:
    handler: handler.handler
    environment:
      DD_SERVERLESS_FLUSH_STRATEGY: 'periodically,60000'
```

We unfortunately can't add config options to the plugin for everything (there's hundreds of config options available in the datadog agent), which is why we are sure to provide environment variables for all of them instead.

Let me know if any of this doesn't make sense. I want to make sure you feel comfortable with this solution. I'm also going to update the public documentation you referenced to make it more clear that `DD_SERVERLESS_FLUSH_STRATEGY` is an environment variable. As it is now, I can see how that would be confusing.
