### ISSUE TITLE
Starting a step function inside a step function fails when passing Input.$ parameter with propagateUpstreamTrace turned on

### ISSUE THREAD

**Issue by meirav-navina** [DataDog/serverless-plugin-datadog#584]
## Expected Behavior
Start a step function execution from another step function with `Input.$` parameter while `propagateUpstreamTrace` flag is set to true.

## Actual Behavior
When trying to deploy the step function an `Cannot have both the field 'Input.$' and the field 'Input' at the same time` exception is thrown.

## Steps to Reproduce the Problem

  1. Set `propagateUpstreamTrace` to true in `serverless.yml`
  ```yaml
  custom:
    datadog:
      site: 'datadoghq.com'
      apiKeySecretArn: ...
      env: ${opt:stage}
      forwarderArn: ....
      enableStepFunctionsTracing: true
      propagateUpstreamTrace: true
   ``` 
  2. Add a startExecution state
  ```yaml
      state_name_1:
        Type: Task
        Resource: arn:aws:states:::states:startExecution.sync:2
        Parameters:
          StateMachineArn: arn:aws:states:us-east-1:123456:stateMachine:other_step_function_name_${opt:stage}
          Input.$: "$"
        OutputPath: "$.Output"
        ResultPath: "$"
        Next: another_state_name
  ```

## Specifications

  - Serverless Framework version:  3.31.0
  - Datadog Serverless Plugin version: 5.67.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 18
  
## Stacktrace
  
  ```
  Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Cannot have both the field 'Input.$' and the field 'Input' at the same time at /States/state_name_1/Parameters, SCHEMA_VALIDATION_FAILED: Cannot have both the field 'Input.$' and the field 'Input' at the same time at /States/state_name_2/Parameters' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: uuid1; Proxy: null)" (RequestToken: uuid2, HandlerErrorCode: InvalidRequest)
  ```

From what I can see there is no logic related to `Input.$` [here](https://github.com/DataDog/serverless-plugin-datadog/blob/main/src/step-functions-helper.ts#L252).

**Comment by lym953** [comment]
Probably the same problem with https://github.com/DataDog/serverless-plugin-datadog/issues/517, which should have been fixed in latest versions. Could you try v5.71.0+?

**Comment by meirav-navina** [comment]
Thanks for the quick response! I updated to the latest version (5.85.0) and got the same error.

**Comment by lym953** [comment]
I see. I reproduced the error. There is indeed no logic related to `Input.$`. Let me see how to fix it.

**Comment by lym953** [comment]
@meirav-navina Unfortunately, due to the limited functionalities provided by Step Function intrinsic functions and JSONPath, I don't think there is an easy way for the Serverless Plugin to add the necessary context into `Input` when you specify it in this way:
```
Input.$: "$"
```
Do you know which specific fields you want to pass to the child state machine? If so, how about writing it in this way?
```
Input.$:
  key1: "$.key1"
  key2: "$.key2"
  CONTEXT.$ = "$$['Execution', 'State', 'StateMachine']";
```

**Comment by meirav-navina** [comment]
I can't pass specific fields, I need the entire previous state.

**Comment by lym953** [comment]
Thanks for the clarification! If you can't pass specific fields, one workaround is to add a separate state like below before your `startExecution` state:
```
InjectContextIntoChildStateMachine:
  Type: Pass
  Parameters:
    CONTEXT:
      Execution.$: "$$.Execution"
      State.$: "$$.State"
      StateMachine.$: "$$.StateMachine"
  ResultPath: "$"
  Next: InvokeChildStateMachineTask
```
This will have billing implications in that it adds a state, but this is the only solution I have given the constraints. However, if you have other states before it, then it might be possible to merge it into another state to save some cost. Does this for you?
