### ISSUE TITLE
`enableStepFunctionsTracing` causes exception when deploying with the `--function <name>` flag

### ISSUE THREAD

**Issue by krewllobster** [DataDog/serverless-plugin-datadog#593]
## Expected Behavior

Running `sls deploy <stack-name> -s <env> --function <function-name>` should deploy just the function code even when the serverless-plugin-datadog config `enableStepFunctionsTracing` is enabled.

## Actual Behavior

Running `sls deploy <stack-name> -s <env> --function <function-name>` fails [during the serverless-plugin-datadog `afterPackageFunction`](https://github.com/DataDog/serverless-plugin-datadog/blob/542ee54ff3ad6bbee0788af72628496e4c32aaac/src/index.ts#L216-L218) with `TypeError: Cannot read properties of undefined (reading 'stateMachines')`

Disabling `enableStepFunctionsTracing` allows the single-function deploy to succeed.

## Steps to Reproduce the Problem

  1. Install `serverless-plugin-datadog`
  2. Install `serverless-step-functions` ensuring that it is listed before `serverless-plugin-datadog`
  3. Add a step function to serverless.yml
```yml
stepFunctions:
  stateMachines:
    myStepFunction: ${file(./serverless/my-step-function.yml):stateMachine}
```

  3. Add an API gateway lambda to serverless.yml
```yml
functions:
  - myLambda:
      handler: src/handlers/my-lambda.handler
      events:
        - http:
            path: '/my-lambda'
            method: GET
```
  4. Set `custom.datadog.enableStepFunctionsTracing` to `true`
```yml
custom:
  datadog:
    addExtension: true
    apiKey: 'my-api-key'
    enableStepFunctionsTracing: true
```
  5. Deploy the whole stack with `sls deploy`
  6. Deploy an update to just the `myLambda` function using `serverless deploy <stack-name> -s <env> --function myLambda`

## Specifications

  - Serverless Framework version: 3
  - Datadog Serverless Plugin version: 5.90
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node v16.13.0 (lts/gallium)
  
## Stacktrace
  
  ```
Error:
TypeError: Cannot read properties of undefined (reading 'stateMachines')
    at ServerlessPlugin.<anonymous> (/.../node_modules/serverless-plugin-datadog/dist/src/index.js:212:95)
    at Generator.next (<anonymous>)
    at fulfilled (/.../node_modules/serverless-plugin-datadog/dist/src/index.js:35:58)
  ```
