### ISSUE TITLE
Ability to global enable/disable plugin (so that can be used for different envs)

### ISSUE THREAD

**Issue by markgibaud-vtail** [DataDog/serverless-plugin-datadog#92]
## Expected Behavior
Want to be able to disable plugin activity (function rewriting etc) for certain envs (eg. personal stacks)

## Actual Behavior
Currently, having this kind of config results in a successful deployment via `sls deploy` but functions fail on execution.

```
dataDogForwarderLambdaArn:
    none: ''
    staging: arn:aws:lambda:us-east-1:blah:function:datadog-ForwarderStack-blah-Forwarder-blah
    prod: arn:aws:lambda:us-east-1:blah:function:datadog-ForwarderStack-blah-Forwarder-blah
  datadogEnabled:
    dev: false
    staging: true
    prod: true
  datadog:
    enableDDTracing: ${self:custom.datadogEnabled.${opt:stackName, 'dev'}, false}
    addLayers: ${self:custom.datadogEnabled.${opt:stackName, 'dev'}, false}
    forwarder: ${self:custom.dataDogForwarderLambdaArn.${opt:stackName, 'none'}, ''}
```
Functions fail with:
```
"errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
```

which I suspect is to do with the plugin "half" doing it's job, eg. having a forwarder with value '' ?

## Steps to Reproduce the Problem

  1. 
  1.
  1.

## Specifications

  - Serverless Framework version: 2.11.1
  - Datadog Serverless Plugin version: 2.10.1
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Node 12.19
  
Note, plugin works as expected for `staging` & `prod` stackNames in this config.
